name: ci

on:
  push:
    tags: - 'v*'

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install envd
        run: |
          pip3 install --pre --upgrade envd -i https://mirrors.sjtug.sjtu.edu.cn/pypi/web/simple
          envd bootstrap
      - name: Build and push
        run: envd build --output type=image,name=${{ github.repository }}:${{ github.ref }},push=true
